# Server
server:
  port: 80

# DataSource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hohodb
    driver-class-name: org.mariadb.jdbc.Driver
    username: *******
    password: *******

mybatis:
  config-location: classpath:/mybatis.xml
